export default {
    SELECT_BOOK: 'SELECT_BOOK',
    SELECT_CATEGORY: 'SELECT_CATEGORY',
    ADD_BOOK: 'ADD_BOOK',
    EDIT_BOOK: 'EDIT_BOOK',
    DELETE_BOOK: 'DELETE_BOOK',
    SEARCH_BOOK: 'SEARCH_BOOK'
}